name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test and Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Build
        run: mvn clean install && ls